
CarBundle\Entity\Car:
    type: entity
    table: car
    uniqueConstraints:
        UNIQ_773DE69DABE530DA:
            columns:
                - cin
    id:
        license:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        model:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        year:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        ownerLn:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: owner_LN
        ownerFn:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: owner_FN
        cin:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            unique: true
    lifecycleCallbacks: {  }
