repare:
    resource: "@RepareBundle/Resources/config/routing.yml"
    prefix:   /

car:
    resource: "@CarBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

